project_name: "Pneumonia Detection"
data:
  raw_path: "data/raw"
  processed_path: "data/processed"
  img_size: 224
  batch_size: 32
  num_workers: 0

train:
  epochs: 10
  lr: 0.0001
  seed: 42
  device: "cuda"

model:
  name: "resnet18"
  num_classes: 2
  pretrained: true
